import NavBar from "@/components/entities/NavBar";
import "./globals.css";
import { Sora } from "next/font/google";
import Header from "@/components/entities/Header";
import Footer from "@/components/entities/Footer";
import BackToTop from "@/components/entities/BackToTop";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Header />
        <NavBar />
        {children}
        <Footer />
        <BackToTop/>
      </body>
    </html>
  );
}
